---
- name: Build Docker container with my Python app
  hosts: localhost

  vars:
    image_name: "pythonapp"
    image_tag: "v1"
    listen_port: 5000
    dockerhub_uname: "dxs01"

  tasks:
    - name: Build Docker image
      docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build
        build:
          path: "."
        state: present

    - name: DockerHub login
      shell: docker login

    - name: Push Docker image
      docker_image:
        name: "{{ image_name }}"
        repository: "{{ dockerhub_uname }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        push: yes
        source: local
        state: present

    - name: Run Docker image
      docker_container:
        detach: yes
        name: old_exercise_python_app
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        published_ports: "{{ listen_port }}:{{ listen_port }}"
