---
apiVersion: v1
kind: Service
metadata:
  name: python-flask-hello-world
spec:
  selector:
    app: python-flask
  ports:
    - name: http-flask
      protocol: TCP
      port: 80
      targetPort: 5000
